### ISSUE TITLE
Add CI tests using github actions

### ISSUE THREAD

**Issue by vissarion** [GeomScale/Rvolesti#2]
We have to write CI yaml scripts that test the R package against various platforms and R versions. 

The scripts from [volesti](https://github.com/GeomScale/volesti) package can be used.

**Comment by Soumya624** [comment]
Hi @vissarion ,

Added a PR, that may solve this issue. Please have a look at [](https://github.com/GeomScale/Rvolesti/pull/5).

Thanks!
