### ISSUE TITLE
GenCube function not defined

### ISSUE THREAD

**Issue by FareheSoheil** [GeomScale/Rvolesti#22]
Following [this documentation](https://volesti.readthedocs.io/en/latest/tutorials/general.html), when trying to estimate the volume of a 3-dimensional cube with `GenCube()` function I get this error:

<pre>Error in GenCube(3, &quot;H&quot;) : could not find function &quot;GenCube&quot;
</pre>

The result of running `help("GenCube")` :
<pre>No documentation for ‘GenCube’ in specified packages and libraries:
you could try ‘??GenCube’</pre>

**Comment by vfisikop** [comment]
Indeed, this tutorial is outdated. You can generate the up to date documentation by following the instructions in https://github.com/GeomScale/Rvolesti?tab=readme-ov-file#documentation the new function is called `gen_cube` see https://github.com/GeomScale/Rvolesti/blob/develop/R/gen_cube.R

**Comment by FareheSoheil** [comment]
Thanks! I could create the updated documentation pdf. and it works.
