### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by vissarion** [GeomScale/Rvolesti#3]
The currect README should be updated (at least) on the following points:

- Update submodule path
- There should not be needed to `cd src/include` when you update the submodule
- Documentation links and credits are outdated
- There is a confusion when referring to `volesti` and `Rvolesti`

**Comment by Soumya624** [comment]
Hi @vissarion ,

A small follow-up. Most of the documentation links are mapping in the `volesti` repository. So, do we need a separate `doc` folder apart from updating the  `README.md`?

**Comment by vissarion** [comment]
I am not sure if we need a separate doc and then a separate documentation
cite. For now it should be ok to link to the R interface of volesti
documentation cite and also the documentation on CRAN website which is
generated by the package in this repo.
